### ISSUE TITLE
add to awesome yazi

### ISSUE THREAD

**Issue by AnirudhG07** [Lil-Dank/lazygit.yazi#2]
Hey! Cool plugin.
Would you like to add it to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? It would nice to put it here as well so that more people can see this.

Thanks!

**Comment by Lil-Dank** [comment]
Hi. Yeah sure, I created a [pull request](https://github.com/AnirudhG07/awesome-yazi/pull/16)
